-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgqi2d6Q+RaYuNEst+
W5JGZYG8O0ZDOKDFRLC8/Boyb52gCgYIKoZIzj0DAQehRANCAASldPXKMpMPdXK7
sJQYLVZwRYXHR4eLqhKfzyqWkhgPA4xMhj86nPGUc86OWeyvKCRdEalvrCW+ae36
/ckw4+L9
-----END PRIVATE KEY-----